-- @BLOCK
-- Table structure for table table_user
CREATE TABLE table_user(
  userId INT UNSIGNED AUTO_INCREMENT,
  userName VARCHAR(40) NOT NULL UNIQUE,
  email VARCHAR(40) UNIQUE NOT NULL,
  phoneNo VARCHAR(10) UNIQUE,
  pwd VARCHAR(40),
  firstName VARCHAR(40),
  lastName VARCHAR(40),
  userImg VARCHAR(40) NOT NULL DEFAULT 'user.png',
  PRIMARY KEY (userId)
);

-- @BLOCK
-- insert into the user
INSERT INTO table_user(`userName`, `email`, `phoneNo`, `pwd`, `firstName`, `lastName`)
VALUES 
('rami123', 'rami123@hotmail.com', '0112525252', '1234', 'Rami', 'Conrad'),
('parker123', 'parker123@hotmail.com', '0252525252', '1234', 'Parker', 'Benitez'),
('osian123', 'osian123@hotmail.com', NULL, '1234', 'Osian', 'Sharples'),
('almond123', 'almond123@hotmail.com', '0552525252', '1234', 'Brandy', 'Almond'),
('noah123', 'noah123@hotmail.com', NULL, '1234', 'Noah', 'Salgado'),
('shiv123', 'shiv123@gmail.com', '0111111111', '1234', 'Shiv', 'Harrison');

-- @BLOCK
-- Table structure for table `table_hotel`
CREATE TABLE table_hotel (
  hotelId INT UNSIGNED AUTO_INCREMENT,
  hotelName VARCHAR(40) NOT NULL,
  hotelDistrict VARCHAR(40) NOT NULL,
  hotelImagePri VARCHAR(40) NOT NULL,
  hotelImageSlide TEXT DEFAULT NULL,
  hotelDescription TEXT NOT NULL,
  hotelFacilities TEXT NOT NULL,
  roomTypes TEXT NOT NULL,
  roomFacilities TEXT NOT NULL,
  hotelWebsite TEXT NOT NULL,
  hotelPhoneNo VARCHAR(12) NOT NULL,
  hotelAddress VARCHAR(60) NOT NULL,
  hotelMap TEXT NOT NULL,
  hotelPrice DECIMAL(10,2) NOT NULL,
  hotelRating DECIMAL(2,1) DEFAULT 0.0,
  PRIMARY KEY (hotelId)
);

-- @BLOCK
-- insert into the hotel
INSERT INTO `table_hotel`(`hotelName`, `hotelDistrict`, `hotelImagePri`, `hotelImageSlide`, `hotelDescription`, `hotelFacilities`, `roomTypes`, `roomFacilities`, `hotelWebsite`, `hotelPhoneNo`, `hotelAddress`, `hotelMap`, `hotelPrice`)
VALUES 
('Weligama Bay Marriott Resort & Spa','Matara','hotel1 (1).jpg','hotel1 (2).jpg,hotel1 (3).jpg,hotel1 (4).jpg,hotel1 (5).jpg,hotel1 (6).jpg,hotel1 (7).jpg,hotel1 (8).jpg,hotel1 (9).jpg,hotel1 (10).jpg','Set right on the beach, Weligama Bay Marriott Resort & Spa offers beach front rooms, a year-round children''s pool, relaxation pool and outdoor lap pool. It also offers water sport facilities and has close proximity to the Galle Fort and Blue Whale watching hubs. The resort also offers a garden with outdoor furniture, a minibar, bathtubs and ironing facilities.','wifi,parking,swimmer,dumbbell,sun','eye,bed-family,bed-delux,bed-bridal','snowflake,wine-bottle,bed,bell','https://www.marriott.com/en-us/hotels/cmbmc-weligama-bay-marriott-resort-and-spa/overview/','041 460 0100','700 Matara Rd, Weligama 81700','https://g.page/MHWeligama?share','44000.00'),
('Amaya Beach Pasikudah','Batticaloa','hotel2 (1).jpg','hotel2 (2).jpg,hotel2 (3).jpg,hotel2 (4).jpg,hotel2 (5).jpg,hotel2 (6).jpg,hotel2 (7).jpg,hotel2 (8).jpg,hotel2 (9).jpg,hotel2 (10).jpg','Amaya Beach Passikudah Resort & Spa Sri Lanka is set next to the beach at Passikudah Bay, a long stretch of coastline renowned for its calm and shallow waters, ideal for swimming and water sports. Besides relaxing on the tranquil beach you will enjoy a wide range of facilities and activities including a large swimming pool, water sports and an award-winning spa.','wifi,parking,swimmer,dumbbell,sun','eye,bed-family,bed-delux,bed-bridal','snowflake,wine-bottle,bed,bell','https://www.amayaresorts.com/amayabeach/','065 205 0200','Pasikudah Rd, Kalkudah 10120 Sri Lanka','https://g.page/AmayaBeachPassikudah?share','18000.00'),
('Anantara Kalutara Resort','Kalutara','hotel3 (1).jpg','hotel3 (2).jpg,hotel3 (3).jpg,hotel3 (4).jpg,hotel3 (5).jpg,hotel3 (6).jpg,hotel3 (7).jpg,hotel3 (8).jpg,hotel3 (9).jpg,hotel3 (10).jpg','Welcome to Anantara Kalutara Resort, your Kalutara “home away from home.” Anantara Kalutara Resort aims to make your visit as relaxing and enjoyable as possible, which is why so many guests continue to come back year after year. <br> St. John''s Church (1.8 mi), located nearby, makes Anantara Kalutara Resort a great place to stay for those interested in visiting this popular Kalutara landmark. <br> Guest rooms offer a flat screen TV, air conditioning, and a minibar, and Anantara Kalutara Resort makes getting online easy as free wifi is available.','wifi,parking,swimmer,dumbbell,sun','eye,bed-family,bed-delux,bed-bridal','snowflake,wine-bottle,bed,bell','https://www.anantara.com/en/kalutara','034 722 6060','St. Sebastian''s Road, Kalutara 12000 Sri Lanka','https://goo.gl/maps/cytm7BNYzA5Lk5iZ6','62000.00'),
('Centara Ceysands Resort & Spa Sri Lanka','Kalutara','hotel4 (1).jpg','hotel4 (2).jpg,hotel4 (3).jpg,hotel4 (4).jpg,hotel4 (5).jpg,hotel4 (6).jpg,hotel4 (7).jpg,hotel4 (8).jpg,hotel4 (9).jpg,hotel4 (10).jpg','On the Bentota peninsula, the Centara Ceysands Resort & Spa Sri Lanka enjoys a superb location with the Bentota River on one side and the Indian Ocean on the other, and is accessed by a short boat ride across the lagoon. The rooms and suites (38-139 sqm. of total living space) feature a balcony or terrace looking out across the peaceful river or over the blue ocean. Truly a family destination in concept, the resort also offers a choice of family-friend accommodation options including Family Residences with bunk beds in a separate children’s area. The resort offers an abundance of natural attractions along with a huge, palm-fringed swimming pool with Jacuzzi, a wealth of water sports including canoeing, sailing, wakeboarding, knee-boarding, and jet skiing, two kids clubs, and a wonderful spa inspired by Thai and Ayurvedic wellbeing heritage. Riverside dining is one of the highlights of the resort which is also home to an authentic Thai restaurant and two bars. Wi-Fi is complimentary.','wifi,parking,swimmer,dumbbell,sun','eye,bed-family,bed-delux,bed-bridal','snowflake,wine-bottle,bed,bell','https://www.centarahotelsresorts.com/centara/ccs/','034 227 5073','Aluthgama - Mathugama Rd, Aluthgama Sri Lanka','https://g.page/CentaraCeysands?share','32000.00'),
('Cinnamon Citadel','Kandy','hotel5 (1).jpg','hotel5 (2).jpg,hotel5 (3).jpg,hotel5 (4).jpg,hotel5 (5).jpg,hotel5 (6).jpg,hotel5 (7).jpg,hotel5 (8).jpg,hotel5 (9).jpg,hotel5 (10).jpg','Sweeping green hills, the longest river in the country, misty mornings and the fresh outdoors, are just a few things that naturally come together here to make the perfect holiday. Just 2 1/2 hours from the Sri Lanka''s Capital City Colombo, Chaaya Citadel Kandy has reinvented itself taking into account the needs of holidaymakers around the world. Replete with a sense of history, serenity and majesty, the hotel offers guests the opportunity to experience the amazing Kandyan history, the culture and the arts that play a big role in the lives of the Sri Lankans.','wifi,parking,swimmer,dumbbell,sun','eye,bed-family,bed-delux,bed-bridal','snowflake,wine-bottle,bed,bell','https://www.cinnamonhotels.com/cinnamoncitadelkandy','011 216 1161','124 Srimath Kuda Ratwatte Mawatha, Kandy 20000 Sri Lanka','https://goo.gl/maps/AUECpnCDEW5MDrb86','20000.00'),
('Citrus Waskaduwa','Kalutara','hotel6 (1).jpg','hotel6 (2).jpg,hotel6 (3).jpg,hotel6 (4).jpg,hotel6 (5).jpg,hotel6 (6).jpg,hotel6 (7).jpg,hotel6 (8).jpg,hotel6 (9).jpg,hotel6 (10).jpg','Citrus Waskaduwa is a five star 150 roomed resort managed by Sri Lanka''s fastest growing leisure company, Citrus Leisure PLC.','wifi,parking,swimmer,dumbbell,sun','eye,bed-family,bed-delux,bed-bridal','snowflake,wine-bottle,bed,bell','http://www.citrusleisure.com/waskaduwa/','011 575 5055','No. 427 Samanthara Road, Waskaduwa 12000 Sri Lanka','https://goo.gl/maps/ockyjZYLNnnRL6827','17000.00');

-- @BLOCK
-- Table structure for table table_hotelReview
CREATE TABLE table_hotelreview(
  hotelId INT UNSIGNED,
  userId INT UNSIGNED,
  rate INT(1) NOT NULL,
  message VARCHAR(100) NOT NULL,
  DATE timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (hotelId, userId),
  FOREIGN KEY (hotelId) REFERENCES table_hotel(hotelId),
  FOREIGN KEY (userId) REFERENCES table_user(userId)
);

-- @BLOCK
-- Table structure for table table_restaurant
CREATE TABLE table_restaurant (
  restaurantId INT UNSIGNED AUTO_INCREMENT,
  restaurantName VARCHAR(40) NOT NULL,
  restaurantDistrict VARCHAR(40) NOT NULL,
  restaurantImagePri VARCHAR(40) NOT NULL,
  restaurantImage1 VARCHAR(40),
  restaurantImage2 VARCHAR(40),
  restaurantImage3 VARCHAR(40),
  restaurantDescription TEXT NOT NULL,
  restaurantMenu VARCHAR(40) NOT NULL,
  restaurantWebsite TEXT NOT NULL,
  restaurantAddress VARCHAR(60) NOT NULL,
  restaurantMap TEXT NOT NULL,
  restaurantPhoneNo VARCHAR(12) NOT NULL,
  restaurantPrice VARCHAR(40) NOT NULL,
  restaurantRating DECIMAL(2,1) DEFAULT 0.0,
  PRIMARY KEY (restaurantId)
);

-- @BLOCK
-- insert into the restaurant
INSERT INTO `table_restaurant`(`restaurantName`, `restaurantDistrict`, `restaurantImagePri`, `restaurantImage1`, `restaurantImage2`, `restaurantImage3`, `restaurantDescription`, `restaurantMenu`, `restaurantWebsite`, `restaurantAddress`, `restaurantMap`, `restaurantPhoneNo`, `restaurantPrice`)
VALUES 
('The Gallery Café','Colombo','restaurant1.jpg','restaurant1_1.jpg','restaurant1_2.jpg','restaurant1_3.jpg',"Paradise Road Galleries -the Gallery Cafe Opened In 1998 In A Structure Which Was The Former Offices Of World Renowned Sri Lankan Architect, The Late Geoffrey Bawa. Bawa Personally Approved Fernando Taking Over His Beloved Property And Converting It Into A Restaurant And Art Gallery And Respected Shanth's Design Sense In The Conversion And Renovation Of The Building To Complement His Own. Bawa's Only Input Was The Location Of The Main Pavilion Where Most Diners Are Seated. The Art Gallery Features Regularly Changing Exhibitions By Established And Emerging Local Artists, For Sale. As The Cafe Is Open From 10AM Through To Midnight Daily, Visitors Frequent The Property For Meals, Site Seeing, Coffee, Cake, Shopping And The Complimentary Wi-fi Available For Use Of Patrons. The Gallery Cafe's Menu Has Not Changed In Years As Regulars Have Their Favourites And Fernando Prides Himself On The Fact That They May Always Return For That Option. It Is Particularly Known For Its Cocktails And Desserts As Well As It's Consistently 'good Food.'",'European, British, Sri Lankan 🍲','https://bit.ly/3C5hZwv','2 Alfred House Rd, Colombo 00300','https://goo.gl/maps/1twxRjXHZDjJFd459','0112 582 162','LKR 2,427 - 10,518'),
('Hilton Colombo','Colombo','restaurant2.webp','restaurant2_1.webp','restaurant2_2.webp','restaurant2_3.webp',"Enjoy a wide range of Breakfast, Lunch & Dinner options tailor made to fit your taste buds or grab a drink whilst indulging in our unique bar bites menu.<br>A village in the heart of the city, Curry Leaf is Colombo's most exclusive Sri Lankan and seafood restaurant.<br>Discover a journey through the richness and flavorsome streets of Cantonese and Szechuan cuisine.<br>Flavours of the world that travels directly to your palatte! Our all-day-dining restaurant, GRAZE Kitchen, is a destination of delicious choices from Chinese, Indian, Italian, Japanese, Mediterranean, Sri Lankan, Thai, and Turkish cuisines.",'European, British, Turkish, Sri Lankan 🍲','https://www.hilton.com/en/hotels/colhitw-hilton-colombo/dining/','2 Sir Chittampalam A Gardiner Mawatha, Colombo','https://g.page/HiltonColomboHotel?share','0112 492 492','LKR 2,427 - 30,518'),
('Curry Leaves','Colombo','restaurant3.jpg','restaurant3_1.jpg','restaurant3_2.jpg','restaurant3_3.jpg',"Take your taste buds on an enchanting indian fantasy with our different Mouth watering dishes",'Indian, Sri Lankan 🍲','https://bit.ly/3HLPEgg','323, B240, Sri Jayawardenepura Kotte','https://goo.gl/maps/EufV1kyB8H7cqtDK9','0711 430 285','LKR 1,500 - 4,000'),
('Seafood Cove','Colombo','restaurant4.jpg','restaurant4_1.jpg','restaurant4_2.jpg','restaurant4_3.jpg',"Seafood Cove is Mt. Lavinia Hotel's specialist seafood restaurant. It has a great location on their private beach front, fast service and reasonably priced, fresh seafood.",'Seafood, Asian, Sri Lankan 🍲','https://bit.ly/3HLPEgg','Station Rd, Dehiwala-Mount Lavinia','https://goo.gl/maps/TVfpt75ecRQLFJd87','0711 430 285','LKR 1,500 - 4,000'),
('Ministry of Crab','Colombo','restaurant5.jpg','restaurant5_1.jpg','restaurant5_2.jpg','restaurant5_3.jpg',"Ministry of Crab was created as a culinary homecoming of Sri Lanka’s legendary lagoon crab, which has long gained popularity outside of the island.<br>The Crabs are the ‘stars of the show’ at Ministry of Crab, ranging from 500g ‘1/2 Kilo’ crab to 2KG ‘Crabzilla’ plated up in a variety of ways from fiery Pepper Crab to the unique Garlic Chilli Crab and the succulent Baked Crab. We also celebrate Sri Lanka’s fine seafood; from amazing King Prawns found in the rivers running across the island to fresh Clams and Oysters from the lagoons.<br>We believe that freshness is of the utmost importance and employ a no-freezer policy in our restaurant to serve you the best dishes using the highest quality ingredients.",'Seafood, Asian, Sri Lankan 🍲','https://ministryofcrab.com/','Old Dutch Hospital Complex, 04 Hospital St, Colombo','https://goo.gl/maps/jUz19tqaqumcQUh29','0770 024 823','LKR 4,500 - 40,000'),
('Graze Kitchen','Colombo','restaurant6.jpg','restaurant6_1.jpg','restaurant6_2.jpg','restaurant6_3.jpg',"A multifaceted restaurant showcasing a live and interactive theater of dining experiences that evoke the senses. Live stations featuring Sri Lankan,Indian,Japanese,Chinese,Italian,Mediterranean, and Thai Specialities will provide key visual and sensory excitement to each area.",'Italian, Chinese, Indian, International, Sushi, Asian, Sri Lankan 🍲','https://www.hiltoncolombo1.com/restaurant/graze-kitchen','2 Sir Chittampalam A Gardiner Mawatha, Colombo','https://goo.gl/maps/oQY8Y6gq35gFzHEA9','0112 492 492','LKR 1,500 - 4,000'),
('Mansoon Colombo','Colombo','restaurant7.jpg','restaurant7_1.jpg','restaurant7_2.jpg','restaurant7_3.jpg',"The monsoons in South East Asian countries affect the style of food cooked across the region, from the way it is sourced to how it is prepared and consumed. At Monsoon Colombo, we revel in the variety of opportunities this offers us!<br>Our chefs regularly visit our suppliers to ensure we use the freshest, locally grown produce available. Our chefs grew up in cultures that value wholesome home cooking and street food, and we take great pleasure in bringing their experience and expertise to you.<br>At Monsoon we bring you some of the regions’ favourite dishes from Malaysia, Singapore, Indonesia, Thailand and Vietnam.",'Thai, Vietnamese, Malaysian 🍲','https://www.monsooncolombo.com/','50, 2 Park St, Colombo','https://g.page/monsooncolombo?share','0112 302 449','LKR 1,500 - 4,000'),
('FLOW','Colombo','restaurant8.jpg','restaurant8_1.jpg','restaurant8_2.jpg','restaurant8_3.jpg',"Launched in 2015, FLOW has paved itself as a destination for dining for entertaining corporate clients or hosting memorable family occasions, the restaurant can offer seating in the main area or provide secluded areas in the three private dining rooms, one of which serves as a Chef’s Table. FLOW is located on the Ground Floor of Hilton Colombo Residences, Union Place, Colombo 02.",'Sri Lankan 🍲','https://www.flow.lk','200 Union Pl, Colombo 00200','https://goo.gl/maps/DKcXX2JZE8MBs8E36','0115 344 644','LKR 1,000 - LKR 3,500'),
('Isso','Colombo','restaurant9.jpg','restaurant9_1.jpg','restaurant9_2.jpg','restaurant9_3.jpg',"Our menu caters to local taste palettes, using only the best quality ingredients from the region. The core concept is prawn centric and our simple three step process allows you to customize your own combo meal by initially selecting the prawn size, followed by the preparation style and the type of carb.",'Japanese, Seafood, Asian, Thai, Sri Lankan 🍲','https://isso.lk','53 Ananda Coomaraswamy Mawatha, Colombo 00300','https://goo.gl/maps/oRcxL2Dgxdj1BCaY9','0117 770 300','LKR 290 - LKR 3,990'),
('Lagoon','Colombo','restaurant10.jpg','restaurant10_1.jpg','restaurant10_2.jpg','restaurant10_3.jpg',"The Lagoon is a fine dining seafood restaurant located in Colombo’s Cinnamon Grand Hotel. Freshly caught seafood is displayed upon a bed of ice and can be chosen with the preferred style of preparation and sides. It’s very good, and very expensive.",'Seafood, Asian, Healthy, Sri Lankan 🍲','https://www.cinnamonhotels.com/cinnamongrandcolombo/experiences/lagoon','77 A2, Colombo 00300','https://goo.gl/maps/Sb7bVbRvSHD1YNp5A','0112 437 437','LKR 3000 - LKR 30,000'),
('Oak Ray Flower Drum Restaurant','Colombo','restaurant11.jpg','restaurant11_1.jpg','restaurant11_2.jpg','restaurant11_3.jpg',"Founded in the year 2002, the Oak Ray Group specializes in Hotel & Restaurant management, and the development of indigenous crafts. With a mission to create a complete Sri Lankan experience for travelers, today it owns a number of Hotels and Resorts across the beautiful landscapes of Sri Lanka.",'Chinese, Asian, Fusion 🍲','https://www.oakrayhotels.com','26 Thurstan Rd, Colombo 00300','https://goo.gl/maps/tbEsdCadj5Wip7LJ8','0112 577 350','LKR 1,012 - LKR 3,035'),
('Shang Palace','Colombo','restaurant12.jpg','restaurant12_1.jpg','restaurant12_2.jpg','restaurant12_3.jpg',"Shangri-La’s signature Chinese restaurant Shang Palace celebrates cuisine steeped in rich tradition. The décor is inspired from Beijing’s traditional siheyuan houses and blends beautifully with modern luxury.",'Chinese, Asian, Fusion 🍲','http://www.shangri-la.com/colombo/shangrila/dining/restaurants/shang-palace/','2, 1 Colombo - Galle - Hambantota - Wellawaya Hwy, Colombo 00200','https://goo.gl/maps/spXrRqbikWGARSrJ9','0117 888 288','LKR 2,000 - LKR 30,000');

-- @BLOCK
-- Table structure for table table_restaurantReview
CREATE TABLE table_restaurantreview(
  restaurantId INT UNSIGNED,
  userId INT UNSIGNED,
  rate INT(1) NOT NULL,
  message VARCHAR(100) NOT NULL,
  DATE timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (restaurantId, userId),
  FOREIGN KEY (restaurantId) REFERENCES table_restaurant(restaurantId),
  FOREIGN KEY (userId) REFERENCES table_user(userId)
);

-- @BLOCK
-- Table structure for table table_vehicle
CREATE TABLE table_vehicle (
  vehicleId INT UNSIGNED AUTO_INCREMENT,
  vehicleName VARCHAR(40) NOT NULL,
  vehicleType VARCHAR(10) NOT NULL,
  vehicleDistrict VARCHAR(40) NOT NULL,
  vehicleImagePri VARCHAR(40) NOT NULL,
  vehicleImage1 VARCHAR(40) DEFAULT NULL,
  vehicleImage2 VARCHAR(40) DEFAULT NULL,
  vehicleImage3 VARCHAR(40) DEFAULT NULL,
  vehicleDescription TEXT NOT NULL,
  vehicleSeats INT(3) NOT NULL,
  vehicleWebsite TEXT NOT NULL,
  vehiclePhoneNo VARCHAR(12) NOT NULL,
  vehicleAddress VARCHAR(40) NOT NULL,
  vehicleMap TEXT,
  vehiclePrice DECIMAL(10,2) NOT NULL,
  vehicleRating DECIMAL(2,1) DEFAULT 0.0,
  PRIMARY KEY (vehicleId)
);

-- @BLOCK
-- insert into the vehicle
INSERT INTO `table_vehicle`(`vehicleName`, `vehicleType`, `vehicleDistrict`, `vehicleImagePri`, `vehicleImage1`, `vehicleImage2`, `vehicleImage3`, `vehicleDescription`, `vehicleSeats`, `vehicleWebsite`, `vehiclePhoneNo`, `vehicleAddress`, `vehicleMap`, `vehiclePrice`) 
VALUES 
('Toyota Prius','Car','Batticaloa','car1.jpg','car1_1.jpg','car1_2.jpg','car1_3.jpg',"Functions :- <ul><li>A/C</li><li>Auto Gear</li><li>5 Passengers</li><li>1 Large Bags 👜</li><li>1 Small Bags 🎒</li></ul><p>Arrange transport for your tour with a popular choice of rent car 🚗 Sri Lanka.</p>",'5','https://bit.ly/3hnEeEw','075 715 0753','Batticaloa City, Batticaloa.','https://goo.gl/maps/JKcQ1zdgCq2CjBeeA','15000.00'),
('KDH Patroof','Van','Colombo','van1.jpg',NULL,NULL,NULL,"Functions :- <ul><li>Full A/C</li><li>Auto Gear</li><li>15 Passengers</li><li>3 Large Bags 👜</li><li>4 Small Bags 🎒</li></ul><p>Arrange transport for your tour with a popular choice of rent Van 🚐 Sri Lanka.</p>",'15','https://bit.ly/3srnx1l','076 027 1417','Piliyandala, Colombo.','https://goo.gl/maps/CLBCz8PgkYYCcJbt9','6000.00'),
('Toyota Premio','Car','Colombo','car2.jpg',NULL,NULL,NULL,"Functions :- <ul><li>A/C</li><li>Auto Gear</li><li>4 Passengers</li><li>1 Large Bags 👜</li><li>1 Small Bags 🎒</li></ul><p>Arrange transport for your tour with a popular choice of rent car 🚗 Sri Lanka.</p>",'4','https://casons.lk/vehicle/toyota-premio-business-class','011 440 6544',' Gothami Road,Rajagiriya','https://g.page/casonsrentacar?share','10000.00'),
('Alphard Ex Lounge','Van','Colombo','van2.jpg',NULL,NULL,NULL,"Functions :- <ul><li>A/C</li><li>Auto Gear</li><li>6 Passengers</li><li>2 Large Bags 👜</li><li>1 Small Bags 🎒</li></ul><p>Arrange transport for your tour with a popular choice of rent Van 🚐 Sri Lanka.</p>",'6','https://casons.lk/vehicle/alphard-ex-lounge','011 440 6544',' Gothami Road,Rajagiriya','https://g.page/casonsrentacar?share','12000.00'),
('Suzuki Every','Van','Colombo','van3.jpg',NULL,NULL,NULL,"Functions :- <ul><li>Full A/C</li><li>Auto Gear</li><li>6 Passengers</li><li>2 Large Bags 👜</li><li>2 Small Bags 🎒</li></ul><p>Arrange transport for your tour with a popular choice of rent Van 🚐 Sri Lanka.</p>",'6','https://lankarentcar.com/','076 327 0269','Baseline Rd, Colombo.','https://g.page/Lanka-Rent-car?share','6000.00'),
('TOYOTA COASTER BUS','Bus','Colombo','bus1.jpg',NULL,NULL,NULL,"Functions :- <ul><li>Full A/C</li><li>With Driver</li><li>27 Passengers</li><li>10 Large Bags 👜</li><li>5 Small Bags 🎒</li></ul><p>Arrange transport for your tour with a popular choice of rent Luxury Bus 🚌 Sri Lanka.</p>",'27','https://www.lankaholidays.com/rent-a-car-van/car-hire_details-44298.html','077 600 9596','Baseline Rd, Colombo.','https://goo.gl/maps/y2DHWqb1e4DNyd3k8','18000.00'),
('Suzuki Alto','Car','Colombo','car3.jpg',NULL,NULL,NULL,"Functions :- <ul><li>Full A/C</li><li>Auto Gear</li><li>4 Passengers</li><li>1 Large Bags 👜</li><li>1 Small Bags 🎒</li></ul><p>Arrange transport for your tour with a popular choice of rent rent car 🚗 Sri Lanka.</p>",'4','https://ikman.lk/en/ad/suzuki-alto-car-for-rent-for-sale-colombo-257','076 209 8120','Baseline Rd, Colombo.','https://goo.gl/maps/y2DHWqb1e4DNyd3k8','18000.00'),
('Toyota Axio','Car','Colombo','car4.jpg',NULL,NULL,NULL,"Functions :- <ul><li>Full A/C</li><li>Auto Gear</li><li>5 Passengers</li><li>2 Large Bags 👜</li><li>1 Small Bags 🎒</li></ul><p>Arrange transport for your tour with a popular choice of rent rent car 🚗 Sri Lanka.</p>",'5','https://ikman.lk/en/ad/toyota-axio-for-rent-for-sale-colombo-161','077 855 3193','Pannipitiya, Colombo.','https://goo.gl/maps/Z1XQmfeZ3KJXcvBt6','38000.00');

-- @BLOCK
-- Table structure for table table_vehicleReview
CREATE TABLE table_vehiclereview(
  vehicleId INT UNSIGNED,
  userId INT UNSIGNED,
  rate INT(1) NOT NULL,
  message VARCHAR(100) NOT NULL,
  DATE timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (vehicleId, userId),
  FOREIGN KEY (vehicleId) REFERENCES table_vehicle(vehicleId),
  FOREIGN KEY (userId) REFERENCES table_user(userId)
);

-- @BLOCK
-- Talbe structrue for table table_package
CREATE TABLE table_package(
  packageId INT UNSIGNED AUTO_INCREMENT,
  packageTitle VARCHAR(40) NOT NULL,
  packageDescription VARCHAR(40) NOT NULL,
  packagePrice DECIMAL(10,2) NOT NULL,
  packageRating INT(1) NOT NULL,
  packageLink TEXT NOT NULL,
  packageImage TEXT NOT NULL,
  PRIMARY KEY (packageId)
);

-- @BLOCK
-- insert into the packages
INSERT INTO `table_package`(`packageTitle`, `packageDescription`, `packagePrice`, `packageRating`, `packageLink`, `packageImage`) 
VALUES 
('Sigiriya Fortress','Tours Available from Monday to Sunday','30000.00',5,'https://www.shatours.com/sri-lanka/sigiriya/', 'sigiriya.jpg'),
('Temple of the Sacred Tooth','Tours Available from Monday to Sunday','15000.00',5,'https://www.shatours.com/4-days-sri-lanka-deluxe-tour/','temple_of_tooth.jpg'),
('Galle Day Tour','Tours Available from Monday to Sunday','10000.00',4,'https://www.shatours.com/negombo-galle-hikkaduwa-tour/','galle_day.jpg'),
('10 Day Holiday Tour','Tours Available from Monday to Sunday','135000.00',5,'https://www.shatours.com/srilanka/tour-packages/10-days-tour/','10_day_tour.jpg'),
('Sacred City of Anuradhapura','Tours Available from Monday to Sunday','45000.00',5,'https://www.shatours.com/negombo-anuradhapura-tour/','anuradhapura.jpg'),
('Whale Watching - Mirissa','Tours Available from Monday to Sunday','35000.00',3,'https://www.shatours.com/sri-lanka/mirissa-beach/','whale_watching.jpg'),
('Udawalawa National Park','Tours Available from Monday to Sunday','15000.00',4,'https://www.tripadvisor.com/Attractions-g674587-Activities-c42-Udawalawe_National_Park.html','udawalawa.jpg'),
('07 Day Holiday Tour','Tours Available from Monday to Sunday','85000.00',2,'https://www.shatours.com/srilanka/tour-packages/7-days-tour/','7day_trip.jpg'),
('Nuwara Eliya','Tours Available from Monday to Sunday','10000.00',5,'https://www.tripadvisor.com/Tourism-g608524-Nuwara_Eliya_Central_Province-Vacations.html','nuwaraeliya.jpg'),
('05 Day Holiday Tour','Tours Available from Monday to Sunday','55000.00',1,'https://www.shatours.com/srilanka/tour-packages/5-days-tour/','5_day_tour.jpg'),
('Sinharaja Forest Reserve','Forests, Nature & Wildlife Areas Viharahena, Sri Lanka','32000.00',4,'https://www.tripadvisor.com/Attraction_Review-g23719828-d447525-Reviews-Sinharaja_Forest_Reserve-Viharahena_Southern_Province.html','sinha.jpg'),
('Royal Botanical Gardens','Gardens, Nature & Wildlife Areas Peradeniya, Sri Lanka','10000.00',5,'https://www.tripadvisor.com/Attraction_Review-g1194819-d523519-Reviews-Royal_Botanical_Gardens-Peradeniya_Kandy_District_Central_Province.html','royal_garder.jpg');

-- @BLOCK
-- Table Structure for table_attraction
CREATE TABLE table_attraction(
  attractionId INT UNSIGNED AUTO_INCREMENT,
  attractionTitle VARCHAR(40) NOT NULL,
  attractionImageHome VARCHAR(40) NOT NULL,
  attractionImagePri VARCHAR(40) NOT NULL,
  attractionDescription TEXT NOT NULL,
  attractionLocationLink TEXT NOT NULL,
  PRIMARY KEY (attractionId)
);

-- @BLOCK
-- insert into the attraction
INSERT INTO `table_attraction`(`attractionTitle`, `attractionImageHome`, `attractionImagePri`, `attractionDescription`, `attractionLocationLink`)
VALUES
('Arthur''s Seat','arthur.webp','arthur.jpg','<p>Located just southwest of Kandy Lake, Arthur''s Seat is one of those places in Sri Lanka that is popular amongst photographers to capture natural beauty. <br><br>The place has an interesting history about how Arthur used to view the city by standing on a stone seat under a tree located in his bungalow.<br><br>From here one can witness the beautiful view of Kandy Lake, Dalada Maligawa, the Temple of the Tooth, and Trincomalee street.</p><br><hr><b>Highlights : </b>Witness the former palace of the Royal family. ,Explore the Buddha on top of a hill<br><br><b>Timings : </b>Open 24 hours','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3957.577493014535!2d80.63761661453533!3d7.288816994739183!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae3662f177fedd7%3A0xe9f7bd6ebfa0619f!2sArthur&#39;s%20Seat%2C%20Kandy!5e0!3m2!1sen!2slk!4v1641398160155!5m2!1sen!2slk'),
('Anuradhapura','anuradapura.jpg','anuradhapura.jpg','<p>Anuradhapura is one of the world heritage site and the place gained importance only after the coming of the Bodhi tree which is known as the tree of enlightenment. <br><br>The cutting of this tree was brought to Sri Lanka by Sanghamitta and is also one of the famous places to see in Sri Lanka.<br><br>The tree is well protected from wild elephants during the reign of King Kirthi Sri Rajasingha. <br><br>It is one of the popular Sri Lanka tourist places to visit.</p><br><hr><b>Location : </b>It is approximately hours from Anuradhapura-Padeniya highway.<br><br><b>Highlights : </b>OApart from the Bodhi tree, you can have a look at the Ruwanwelisaya which is one of the magnificent stupas.<br><br><b>Best time to visit : </b>April and September.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d126325.57066635639!2d80.33327282129981!3d8.335145709609428!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3afcf4f99360e159%3A0xc111fe9ebc6dcf0e!2sAnuradhapura!5e0!3m2!1sen!2slk!4v1641400746712!5m2!1sen!2slk'),
('Attidiya Bird Sanctuary','attidiya.webp','attidiya.jpg','<p>This is probably the only place in Colombo that provides shelter to at least 50 different species of birds (both local and migratory). </p><br><b>Highlights : </b>A large number of water monitors, butterflies, insects and other birds tend to catch your attention as you walk through the muddy paths of the sanctuary. The biodiversity of this place is highly commendable, as you cannot help but feel awe-struck at the diverse species of birds here. As the place is replete with mosquitoes, you need to be fully covered while visiting the park. <br><hr><b>Location : </b>The sanctuary is located at Boralesgamuwa in Colombo. <br><br><b>Timings : </b>The sanctuary is open all through the day; however early mornings and evenings are best to visit migratory birds.<br><br><b>Price : </b>Entry to the place is free of cost.<hr><br><br><br>','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3961.4459660333123!2d79.88847871453254!3d6.837013795058858!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae25aec90414727%3A0xdd8be9b10e1246cb!2sAttidiya%20Bird%20Sanctuary!5e0!3m2!1sen!2slk!4v1641401250250!5m2!1sen!2slk'),
('Babarakanda Waterfall','babarakanda.jpg','babarakanda.jpg','<p>Mark it on your bucket list to visit this one of the most tranquil place while you are in Sri Lanka. <br><br>With a sheer drop of waterfall from a height of 263 meters Bambarakanda Falls is one of the highest waterfalls in Sri Lanka. <br><br>The dazzling waterfall lies in the Badulla District among evergreen forest in the Kalupahana Area.</p><br><hr><b>Highlights : </b>The fall is framed by the Uduweriya Haputale Mountain and Kuda Oya, a tributary of Walawe River.<br><br><b>Location : </b>The Bambarakanda Falls is located at Kalupahana - Ohiya Rd, Sri Lanka<br><br><b>Price : </b>The entry is free in the waterfalls<hr><br><br><br>','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3961.9712655567932!2d80.82902511453213!3d6.773351695104018!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae47660d0e3ef59%3A0x6863b33a5baad25!2sBambarakanda%20Falls!5e0!3m2!1sen!2slk!4v1641401573192!5m2!1sen!2slk'),
('Bahiravakanda','bahiravakanda.jpg','bahirava.jpg','<p>This place showcases a breathtaking view of the entire Kandy town. <br><br>The 88ft high statue of Buddha is something one should not miss while in Kandy. <br><br>The white statue can be seen from any part of the Peradeniya city as it is strategically located on top of the Bahirava Kanda (devil’s) hill.<br><br>You can either climb the steps to reach the viewpoint or else hire a tuk-tuk to do so. <br><br>The beauty of the statue doubles during the night when it is lit by lamps. <br><br>Best hour to visit this place is early morning or after sunset. <br><br>This place should be definitely there on your list of places to visit in Sri Lanka.</p><br><hr><b>Location : </b>Peradeniya, Kandy.<br><br><b>Timings : </b>Open 24 hours a day.<br><br><b>Price : </b>Approximate price starts from 200 LKR.Approximate price starts from 200 LKR.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3957.5178656658863!2d80.62876841453544!3d7.295563094734433!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae368804222a85d%3A0xbe9691c716dc1fc4!2sBahirawakanda%20Vihara%20Buddha%20Statue!5e0!3m2!1sen!2slk!4v1641401851661!5m2!1sen!2slk'),
('Balapitiya Beach','balapitiya.webp','balapitiya.jpg','<p>Situated 80 km south of Columbo, Balapitiya provides a vital Sri Lankan atmosphere with a spectacular two-hour drive through a coastal route. <br><br>With beautiful sandy beaches, this remote and visually beautiful fishing village stays pretty untouched by mass tourism.<br><br>Witness how the beach boundaries were smattered by tiny fishing hamlets. <br><br>Discover nearby attractions, such as the  CityGalle and Ambalangoda''s popular mask carvings. <br><br>Surfers can also bask in the wave bliss of Hikkaduwa.</p><br><hr><b>Highlights : </b>A haven for birdwatchers and adventure enthusiasts.<hr><br><br><br>','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3965.7769766688566!2d80.0354097645293!3d6.293014845445387!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae1809369eda4b3%3A0xc78d432c38b70464!2sBalapitiya%20Beach!5e0!3m2!1sen!2slk!4v1641402109891!5m2!1sen!2slk'),
('Bentota Lake','bentota lake.webp','bentota.jpg','<p>Snuggled between the town''s coast and the city, Bentota Lake lets the travelers enjoy a fantastic meal while having them experience the stunning views of the lake. <br><br>You will also witness beautiful birds and fishes along the shores of this serene lake.<br><br>For those seeking a vacation from the hustle-bustle of the city and who would love to indulge in sport and tourist activities, this lake will prove to be perfect.</p><br><hr><b>Highlights : </b>The name of the town is derived from the name of a demon called “Bem". <br><br>Snorkeling, diving, water-skiing, sailing, windsurfing, and fishing can be done here. <br><br>Tropical palm trees and sunset are the most amazing views.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3964.773164898816!2d79.99565281453005!3d6.423184245352751!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae22e9a76e06153%3A0x3b3da8525812224!2sBentota%20Lake!5e0!3m2!1sen!2slk!4v1641402885717!5m2!1sen!2slk'),
('Mahamevnawa','mahamevna.jpg','mahamewna.jpg','<p>The Mahamevnawa Monastery is one of the most important and revered Buddhist temples in Sri Lanka founded by Ven. <br><br>Kiribathgoda Gnanananda Thero and is amongst the top places to visit in Ella. <br><br>This monastery serves as an educational institution for young people and adults who want to be ordained as monks. <br><br>Sri Lankan artists have adorned the Monastery with striking carvings, murals, and painting. <br><br>Here, you can not only talk freely to the monks but also take personalised meditation lectures from them. <br><br>Listening to the reverberating Buddhist hymns amidst the peaceful environs is a tranquil experience. </p><br><hr><b>Location : </b>Bandarawela, Ella<br><br><b>Timings : </b>8:00 am- 9:00 pm every day of the week','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3961.091180011939!2d81.02570321453283!3d6.879679295028616!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae464fe217475f3%3A0x1df939d1b9fd60c9!2sMahamevnawa%20Buddhist%20Monastery%20-%20Bandarawela!5e0!3m2!1sen!2slk!4v1641435299673!5m2!1sen!2slk'),
('Beira Lake','bere.jpg','beira_lake.jpg','<p>If there is one place where you can get the combined benefits of adventure, pilgrimage, picnic and fun, it is the Beira Lake. <br><br>This is one of the hot tourist spots in Colombo as well. <br><br>One can enjoy duck paddle boat rides on the lake. <br><br>It is one of the famous places to visit in Colombo..</p><br><hr><b>Location : </b>Located quite close to the famous Gangaramaya Temple, Beira Lake offers an excellent view of the temple, especially in the evenings, when the temple is fully illuminated. <br><br><b>Timings : </b>The lake is open all through the year to enable visitors; however evenings are the best to come here to get a panoramic view of the temple. <br><br><b>Price : </b>Approximate price is 300 LKR however if you have paid for entry into the Gangaramaya temple, that will suffice here as well.Approximate price is 300 LKR however if you have paid for entry into the Gangaramaya temple, that will suffice here as well.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15842.856824636277!2d79.84482952317796!3d6.924726369946542!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae2591640b4e0b3%3A0x14fcac803e83edbd!2sBeira%20Lake!5e0!3m2!1sen!2slk!4v1641402531738!5m2!1sen!2slk'),
('Buddhist Museum','bumuseum.jpg','international_buddhi.jpg','<p>Located close to the Temple of the Tooth, inside the royal palace complex, The International Buddhist Museum is a complete knowledge base and a showcase of the spread of Buddhism throughout Asia. <br><br>It is one of the famous religious places to visit in Sri Lanka.<br><br>There are separate rooms dedicated to different countries illustrating Buddhism in that location. <br><br>There are photographs, models and gigantic statues which portray the spread and influence of Buddhism on people in various places.</p><br><hr><b>Location : </b>Close to Temple of Tooth, Kandy<br><br><b>Time : </b>8:00 AM to 7:00 PM<br><br><b>Price : </b>Approximate price starts from 1070 LKR per adult<br><br><b>Highlights : </b>To get a better knowledge about the spread of Buddhism displayed here one can opt for a free audio guide which is available at the ticket counter or can opt for a tourist guide at 1070LKR who explains the whole location. <br><br>Do wear covered clothes from shoulder to toe and remove the shoes. <br><br>There’s an elevator in the Museum which allows disabled visitors to access the Museum.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3957.531453941047!2d80.63966151453539!3d7.294026294735508!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae3662dbba8562d%3A0xcf892bc819b4519f!2sWorld%20Buddhist%20Museum!5e0!3m2!1sen!2slk!4v1641403257141!5m2!1sen!2slk'),
('Cricket Museum','cricket.webp','cricket.jpg','<p>Situated at Maitland Place, Colombo, this museum is popular for displaying the entire history of Sri Lanka''s cricket. <br><br>One can spot the many trophies won in the World Cup and T20 competitions. </p><br><hr><b>Highlights : </b>A ‘Hall of Fame’ which displays the names of Sri Lanka’s test players. Displays the significant moments of Sri Lanka''s cricketing history.<br><br><b>Entry fee : </b>Non – Residents<br><br>Adults-LKR 500<br><br>Children – LKR 300<br><br>Adults – LKR 100','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11202.942449627471!2d79.85003314866256!3d6.909931321236097!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae2597bd1019385%3A0x7e8554e207a2abdb!2sSri%20Lanka%20Cricket!5e0!3m2!1sen!2slk!4v1641403592191!5m2!1sen!2slk'),
('Dambulla','dabulla_cave.jpg','dambulla.jpg','<p>Dambulla Cave temple is also known as the Golden Rock temple is also one of the world heritage city declared by UNESCO. <br><br>The cave temple is made with a massive granite outcrop.<br><br>The word ‘Damba’ means rock and ‘Ulla’ means fountain, hence you can see drip of water from the main house. <br><br>If you have an eye for paintings then you can also see some of the historic paintings which shows the majestic manifestation of the first sermon of Buddha.</p><br><hr><b>Location : </b>You can come via Ambepussa and Kurunegala which is approximately 4 hours from Colombo.<br><br><b>Price : </b>There are no prices charged for the same, however you have to pay  200 LKR for keeping the luggage.<br><br><b>Highlights : </b>Don’t forget to visit the Golden temple Buddhist museum which will leave you jaw dropped with its spectacular entrance from the golden mouth of lion like beast.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3952.367072163501!2d80.64632541453922!3d7.856597794339311!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3afca558c5bd3669%3A0xd1daa5c0936b764c!2sDambulla%20Royal%20Cave%20Temple%20and%20Golden%20Temple!5e0!3m2!1sen!2slk!4v1641403879862!5m2!1sen!2slk'),
('Dhowa','dhowa.jpg','dhowa.jpg','<p>Located in the central mountains of the Uva province, Dhowa Rock Temple is a protected heritage site in Sri Lanka. <br><br>The Dhowa rock temple is popular for its massive incomplete Buddha image, etched into the rock face, which is deemed an illustration of Mahayana sculpture.<br><br>The temple goes all the way back over two thousand years and is considered to be the best Sri Lanka tourist places.</p><br><hr><b>Highlights : </b>The Dhowa temple was known as the Kumbaltissa Ariyagala Vehera. <br><br>It''s called Dhowa because it is situated within a ring of mountains, with a river that flows across the plateau.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3961.285627943056!2d81.01997051453263!3d6.856328295045179!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae46572f291905b%3A0x5bf54fa9fa48a0d1!2zRG93YSBSYWphbWFoYSBWaWhhcmF5YSDgtq_gt53gt4Ag4La74Lai4La44LeE4LePIOC3gOC3kuC3hOC3j-C2u-C2ug!5e0!3m2!1sen!2slk!4v1641404114442!5m2!1sen!2slk'),
('The Doctors House','doctor.jpg','doctor.jpg','<p>The Doctor''s House is a 200-year-old former Dutch and Ayurvedic hospital, located in the magnificent town of Madiha on Sri Lanka''s south coast. <br><br>It''s the result of a few Australian fellows who freely confess that they have no hospitality experience, but are simply trying to have some fun while facilitating and building a nice atmosphere.<br><br>They serve pizzas, snacks, desserts, cocktails, and beers and have 2 dorm rooms available, it is certainly the most unique places to visit in Sri Lanka.</p><br><hr><b>Highlights : </b>Rent boars and go snorkeling or surfing nearby.<br><br>Stay at the place and play games and eat delicious pizzas.<br><br><b>Timings : </b>Fri, Sat, Sun- 12-10pm','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3968.4205862894955!2d80.5139130145274!3d5.936619995699523!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae13ee425601aa7%3A0x4c0748c1f0d8c915!2sThe%20Doctor&#39;s%20House!5e0!3m2!1sen!2slk!4v1641404427009!5m2!1sen!2slk'),
('Ella','ella.jpg','ella.jpg','<p>Ella is popular for its lush greenery and the cool and collected environment amongst the people. <br><br>Ella Rock is a popular hiking and camping destination and it is a delight to witness spectacular views with haze and clouds surrounding the area.<br><br>The average time it takes to climb up and down is 4 hours making it the most loved Sri Lanka tourist place for trekkers.</p><br><hr><b>Location : </b>Sitting on the hills just 2.5 kilometers above Ella Town.<br><br><b>Highlights : </b>Takes you through beautiful and dense forests','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15844.843690152979!2d81.03859227317213!3d6.865308920620182!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae465955bc09a25%3A0xbdfadcdadec487fb!2sElla!5e0!3m2!1sen!2slk!4v1641431031702!5m2!1sen!2slk'),
('Galle Fort','lighthouse.jpg','galle.jpg','<p>Galle''s history goes way back thousands of years. <br><br>It is a perfectly preserved colonial Dutch fort with a tiny little town with cobblestone streets inside. <br><br>This is one of those places in Sri Lanka where you can also find serene beaches, rainforests, and other attractions to be close. <br><br>It is certainly an intriguing place to explore and is a haven for nature lovers.</p><br><hr><b>Highlights : </b>It is a Portuguese fortress that was built in 1588.<br><br> It is a UNESCO world heritage site.<br><br>You can find shops, cafes, exhibitions, villas close by.<br><br><b>Timings : </b>Open 24 hours<br><br><b>Price : </b>National Maritime Museum – 65 LKR<br><br>Galle Fort Ramparts – 45 LKR','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7935.525433453858!2d80.2123322732217!3d6.027272282539214!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae173a6a024d64d%3A0x569ac10c90e0fa7c!2sFort%2C%20Galle%2080000!5e0!3m2!1sen!2slk!4v1641431337291!5m2!1sen!2slk'),
('Galle Face Green','galleface.jpg','galle_face.jpg','<p>Avid Joggers, walkers and kite flyers for whom honking horns are a big turn off. <br><br>We have Galle Face Green, a beautiful stretch of lawn facing the sea right in the very heart of Columbo. <br><br>You will breathe, the way a person from a crowded city would love to. <br><br>This place is bustling with life all the time. It is one of the best places to visit in Sri Lanka.<br><br>For people who don’t mind putting on that extra calorie can try some street side food from the local hawkers, who gather there to fill up your stomach with some tasty food.<br><br>The local food is too hard to resist for food lovers who would love to tickle their palate with the same</p><br><hr><b>Highlights : </b>If you breathe shopping then this place is aptly for you. You can buy hand-loomed bedspreads, cushion covers, lampshades available at different price range from Designer Barbara Sansoni which is located in old villa.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3960.7128089012153!2d79.84224181453305!3d6.924892794996613!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae259396a72f305%3A0x5e7e24c6bf94136f!2sGalle%20Face%20Green!5e0!3m2!1sen!2slk!4v1641321726116!5m2!1sen!2slk'),
('Gangaramaya Temple','gangaramaya.jpg','gangaramaya.jpg','<p>Gangaramaya Temple is not only one of the most beautiful but also one of the most iconic Buddhist temples in Sri Lanka. <br><br>It is more than a century since this temple was constructed; however even today, the temple doesn’t stop to surprise tourists and devotees and is therefore one of the best tourist places in Colombo.<br><br>The pathways and doors that lead into the main sanctum sanctorum contain intricately carved sculptures that are simply breath-taking. </p><br><hr><b>Location : </b>The temple is located right on the Jinaratana Road in the heart of Colombo city. <br><br><b>Timings : </b>The temple is open from 5.30AM to 10PM. <br><br><b>Timings : </b>The temple is open from 5.30AM to 10PM. <br><br><b>Highlights : </b>The ceilings and walls contain pictures and miniature paintings that explain stories from Buddhism religion. In the main sanctorum, a huge Buddha statue exudes a brilliant sense of calmness in the devotees. Built in a mix of various architectural styles including India, Burmese, Thai and Chinese, this temple also houses a museum. ','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3960.7816056664574!2d79.85445751453305!3d6.916693795002393!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae2596b9982dc43%3A0x3a35356ebd5eed36!2sGangaramaya%20Temple!5e0!3m2!1sen!2slk!4v1641431634773!5m2!1sen!2slk'),
('Horton Plains','horton.jpg','horton.jpg','<p>Horton National Park is a ‘food for the soul’ kind of mesmerizing locale. <br><br>The park is perched in the shadows of the country’s 2nd and 3rd highest mountains, Kirigalpota and Totapola. <br><br>The place is also termed as world’s end due to its undaunting mysterious views of waterfalls, misted lakes and earthy species of flora and fauna. <br><br>The national park is actually a plateau and is 2000m high. <br><br>It is better to start early in the morning to witness this heavenly place.</p><br><hr><b>Location : </b>11 kms approx from Ohiya.<br><br><b>Timings : </b>6 am to 6 pm<br><br><b>Highlights : </b>An array of wildlife such as Samba deers, leopards, wild boars, purple faced langoor; an ideal site for birdwatchers as you may encounter a variety of flying wonders such as bulbul, Ceylon blackbird, Ceylon white eyed arrenga, mountain hawk etc; the epic walk to world’s end(4kms) and Farr Inn hunting lodge.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3961.728772518996!2d80.8069077145323!3d6.802813595083108!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae3882edb4b78ef%3A0xcebca89153777249!2sHorton%20Plains%20National%20Park!5e0!3m2!1sen!2slk!4v1641432208690!5m2!1sen!2slk'),
('Independence Square','inependence.jpg','ind.jpg','<p>Independence Memorial Hall in Colombo, as the name indicates, was constructed to commemorate the occasion of Sri Lankan Independence from British Rule. <br><br>The construction of this memorial was completed during 1953. </p><br><hr><b>Location : </b>The hall is located in Cinnamon Gardens and was formerly known as Torrington Square.<br><br><b>Timings : </b>This hall is open all through the year. <br><br><b>Highlights : </b>When you come here, you ought to visit the Independence Memorial Museum as well, which honours the people who fought for Sri Lankan Independence. Currently, this hall is the venue where Independence Day celebrations and other national events are being held. <br><br>Prior to the construction of the Sri Lankan Parliament, this Memorial Hall served as the ceremonial assembly as well. This place currently caters to the needs of fitness enthusiasts as the open spaces here are used for jogging, cycling, public gym, aerobic sessions and other relevant activities.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3960.881573956585!2d79.86502961453296!3d6.904762595010848!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae2597b88958e0b%3A0xc1c5089f26bc260b!2sIndependence%20Square!5e0!3m2!1sen!2slk!4v1641432511829!5m2!1sen!2slk'),
('Kande Viharaya','kande vihara.webp','kande_vihara.jpg','<p>Kande Vihara is the Kalutara district''s largest Buddhist temple. <br><br>The name of the temple typically means ''Mountain Temple'' and was named this because it was built close to Aluthgama town on the crest of a hill. <br><br>It is also known to be an officially recognized Archaeological Site of Sri Lanka.<br><br>Since it was unveiled in 2007, the colossal statue at this ancient temple has been popularly attracting more and more tourists.</p><br><hr><b>Highlights : </b>It features the Stupa, Bo Tree, Relic Chamber, Image House, Sri Vishnu Temple.<br><br>Kande Vihara has a bell-shaped stupa erected within an octagonal shelter.<br><br><b>Timings : </b>5 am- 8 pm','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3964.569335275397!2d79.99860751453024!3d6.449296295334159!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae22e705e524e27%3A0x722cefdb2c6db609!2sKande%20Viharaya%20Temple!5e0!3m2!1sen!2slk!4v1641433995328!5m2!1sen!2slk" width="1150'),
('Kandy','kandy.webp','temple_of_the_tooth.jpg','<p>It is situated on the Rajapihilla Mawatha. Being very close to the lake, this place even gives away mesmerizing views of mountains and meadows. <br><br>In just a little climb, you will find yourself standing in front of one of the best places to visit in Sri Lanka. </p><br><hr><b>Highlights : </b>Panoramic view of the city <br><br>You can buy souvenirs <br><br>Explore the art galleries','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3957.5315273213205!2d80.6408666145354!3d7.294017994735525!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae36766e482c83b%3A0x95c37e6f3a8ba54c!2sKandy%20View%20Point%20-%20Udawattakele%20%E2%9B%B0!5e0!3m2!1sen!2slk!4v1641434282717!5m2!1sen!2slk'),
('Koggala','koggala.jpg','koggala_beach.jpg','<p><b>Koggala Lake :</b> A lagoon situated near the Beach, the Koggala Lake is one of the most serene corners of the country. <br><br>Abounding in rich plant and marine life, the Koggala Lake is embellished with eight small scattered islands. <br><br>The island consists of lush mangrove swamps which serve as nurseries for various species of fish, as well as a number of creatures such as barnacles or oysters.</p><br><hr><b>Location : </b>Galle, Sri Lanka.<br><br><b>Timings : </b>09.00 AM-03.00 PM on all days of the week.<br><br><b>Entry Fee : </b>No entry fee is required to visit the lake. Guide tours across the lake would cost between LKR 3,500- LKR 4,000.<br><br><br></section><section><p><b>Sea Turtle Farm & Hatchery :</b> With the goal to protect the dwindling population of the native sea turtles, the Koggala Sea Turtle Farm and Hatchery aims to provide the species with medical aid and protection and thus improve their rate of survival. <br><br>Visitors to the Turtle Farm get a comprehensive insight into the working of the project here. Visitors may also interact with the turtles housed here, or release a grown turtle into the sea under the guidance of the farmhands.</p><br><b>Location : </b>Koggala Sea Turtle Farm & Hatchery, Matara Road, Koggala.<br><br><b>Timings : </b>08.00AM- 06.00PM on all days of the week.<br><br><b>Entry Fee : </b>Rs. 500 per person for an ordinary entry ticket / Rs. 1500 per person to release a turtle into the sea<hr><br><br><br></section>','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31743.539013248468!2d80.31380830268597!3d6.002651121746824!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae16ccc65d32a85%3A0x47fdbb4441fdf8bf!2sKoggala!5e0!3m2!1sen!2slk!4v1641434566509!5m2!1sen!2slk'),
('Sorabora Lake','mahiyanganaya.webp','sorabora_lake.jpg','<p>Lush greenery, tropical climate and wilderness camping is the key essence of visiting Mahiyanganaya Sorabora Lake. <br><br>This is a manmade lake believed to be constructed by King Dutugemunu''s betel supplier named Bulata. <br><br>Counted as one of the most incredible places to visit in Sri Lanka.<br><br>There is a beautiful sluice gate here which is a known to be quite old built in around 162 BC but believed to be still in use.<br><br>Camping here is a pleasure with unlimited leisure options of fishing and enjoying boat ride on the lake. <br><br>The scenic extravaganza, especially during the sunrise and sunset time, is simply breathtaking.</p><br><hr><b>Location : </b>Uva Province, Sri Lanka<br><br><b>Best Season : </b>Throughout the year<br><br><b>Highlights : </b>Fish viewing and bird watching','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31655.300576141504!2d81.00545415320917!3d7.363696709918886!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae4bd7178c993fb%3A0x41fea5b90083f74a!2sHorabora%20Wewa!5e0!3m2!1sen!2slk!4v1641435590967!5m2!1sen!2slk" width="1150'),
('Mirissa','mirissa.jpg','mirissa.jpg','<p>Mirissa is a tiny village on Sri Lanka''s south shore, situated in the Southern Province of Matara District. <br><br>It is the south coast''s largest fishing port and is popular for its tuna, mullet, snapper, and butterfish. <br><br>If you''d like to experience a mesmerizing sunset dinner with beautiful scenic views, then Mirissa beach is the place to be at.<br><br>It comes amongst the must-visit Sri Lanka places as you will find a lot of restaurants to be serving the most delicious seafood.</p><br><hr><b>Highlights : </b>Witness whales and dolphins from afar.<br><br>Enjoy nightlife and seafood.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3968.3707413926454!2d80.45653931452746!3d5.943536695694579!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae13fd4c636d5ff%3A0xb81456b9b41a93b2!2sMirissa%20Beach!5e0!3m2!1sen!2slk!4v1641435855758!5m2!1sen!2slk'),
('Moragalla','moragalla.webp','moragalla.jpg','<p>Moragalla Beach is a paradise for beach lovers, especially for anyone who is looking for a deserted beach trip, as it is mostly peaceful and not noisy at all. <br><br>Owing to the submerged coral reef that sits not far from the coastline, the sea surrounding Moragalla is very shallow.<br><br>It has clear blue water and is an excellent spot for water activities such as windsurfing, diving, and snorkeling. <br><br>The gorgeous clean sandy beach is excellent for daily walks and watching the mesmerizing sunset.</p><br><hr><b>Highlights : </b>There is a tiny island in front of the beach.<br><br>The beach is ideal for adventure activities like snorkeling, surfing, etc.<br><br><b>Timings : </b>6 am- 6 pm','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7929.191256671916!2d79.9801254232311!3d6.4459338813461935!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae22e5d165433bf%3A0x8758469f9f34933f!2sMoragalla%20Beach!5e0!3m2!1sen!2slk!4v1641436045393!5m2!1sen!2slk'),
('National Museum','museum.webp','national_museum.jpg','<p>If you are a history lover and have a keen eye for architecture, the National Museum is probably one of the first few places to visit in Colombo.<br><br>Established during 1877, this is the biggest museum in the island nation and is undoubtedly the pride of Sri Lanka. <br><br>The place houses some of the best and personalised collections of the ancient Kandyan dynasty rulers. </p><br><hr><b>Location : </b>The museum built in Italian architecture style, is located right in the heart of the Colombo city. <br><br><b>Timings : </b>The museum is open on all days except national holidays from 9:00 AM to 6:00 PM. <br><br><b>Price : </b>Approximate price for local adults and kids are 35 LKR and 20 LKR respectively, whereas, for foreign adults and kids, the prices are 600 LKR and 300 LKR respectively.<br><br><b>Highlights : </b>The museum’s library deserves special mention as it contains rich manuscripts in palm leaves in languages like Burmese, Sinhala, Telugu, Tamil and much more.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3960.833896115405!2d79.85880381453302!3d6.910455495006771!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae2596fa1f4b2af%3A0xd90a283d68f9a48d!2sColombo%20National%20Museum!5e0!3m2!1sen!2slk!4v1641436347492!5m2!1sen!2slk'),
('Pinnawala','pinnawala.webp','pinnawala.jpg','<p>Peradeniya Gardens is a spacious 147 acre of natural extravaganza consisting of more than 4000 species of plants, and 10,000 varied kinds of trees, incidentally serves as the largest garden in Sri Lanka and is one of the best places to visit in Sri Lanka. <br><br>The unique and rarest collection in these gardens is the Giant Bamboo of Burma which grows 12 inches each day to a height of 40 meters. <br><br>Apart from this other amazing collections include Javan fig tree, Cannonball tree, Double Coconut Palm and about 200 other varieties of palm trees and versatile collection of flora. </p><br><hr><b>Timings : </b>Opened daily from 7:30 AM to 5:00 PM<br><br><b>Highlight : </b>One can pack some food to enjoy an open-air picnic here or can relish the cafeteria inside serving local and western cuisine. <br><br>The Peradeniya Botanical Garden is one prime tourist attraction of hill country and remains quite flooded with tourists every weekend. ','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3957.470031190129!2d80.38496225009597!3d7.300970494704762!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae315c83a2c0273%3A0xa5744b525ada1e6c!2sElephant%20Orphanage!5e0!3m2!1sen!2slk!4v1641437277160!5m2!1sen!2slk'),
('Panadura Beach','panadura.jpg','panadura.jpg','<p>Famous for providing a spacious shoreline for kite flying and a kid’s play area, Panadura beach is an ideal place to have a fun gathering and spending quality time with your loved ones. <br><br>It is even appropriate for jogging, running, exercising, and more along with scrumptious seafood available nearby.</p><br><hr><b>Location : </b>Situated just 16 km from Kalutara towards Colombo. <br><br><b>Highlights : </b>Golden sandy and infinite waves.<br><br>Children''s play area.<br><br>Panadura is a fishing town.<br><br> Street food and restaurants are available. ','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3962.47704060855!2d79.89983355009227!3d6.711487895124067!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae24615d8f8355d%3A0x8d7c1ff79f079a4d!2sPanadura%20Beach!5e0!3m2!1sen!2slk!4v1641436637954!5m2!1sen!2slk'),
('Polhena Beach','polhena.webp','polhena.jpg','<p>The perfect spot to indulge in swimming, snorkeling, and sunbathing, Polhena Beach provides tourists with a perfectly thrilling beachside. <br><br>The beach is also famous as a great romantic getaway spot due to its iconic romantic feel and look.</p><br><hr><b>Highlights : </b>Enjoy water sports at the beach.<br><br>Witness turtles if the visibility is fine.<br><br>Rent inflatable toys and frolic in the surf.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3968.423922614189!2d80.52389050008786!3d5.93615674567876!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae13edc620bad4d%3A0x6591c62a45627498!2sPolhena%20Beach!5e0!3m2!1sen!2slk!4v1641437471597!5m2!1sen!2slk" width="1150" height="550'),
('Polonnaruwa','pollonnaruwa_3.jpg','polonnaruwa.jpg','<p>Just walk into the Golden age by entering the city of Polonnaruwa which is not only its capital but also an ancient kingdom of Sri Lanka too. <br><br>You will find some of the ancient remains of palaces, shrines and stupa. <br><br>It is amongst the highly visited Sri Lanka tourist places.<br><br>Each of these historical remains is blessed with a glorious past of their own.<br><br>Once you have reached the place it will keep you glued to it that you wouldn’t even realize when time flies by.</p><br><hr><b>Location : </b> Approximately a 5 hour drive from Colombo<br><br><b>Highlights : </b>You shouldn’t miss the chance to see the statue of Parakramabahu I who had his reign during the golden age. <br><br>You can also witness a spectacular view of the Lotus Pond with its lotus-shaped petals built on 4 tiers, the majestic view is not supposed to miss.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3951.511816171383!2d80.99813535010037!3d7.945942494248523!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3afb456e05e5a4c9%3A0x72cd1cfea9d4d0a9!2sPolonnaruwa%20Ancient%20City!5e0!3m2!1sen!2slk!4v1641437712934!5m2!1sen!2slk'),
('Sinharaja forest','sinharaja.jpg','sinharaja.jpg','<p>Declared as a World Heritage Site by UNESCO, Sinharaja Forest Reserve (kingdom of the lion), is a paradise for nature and wildlife lovers. <br><br>It is home to a vast number of endemic species of birds and mammals of Sri Lanka. <br><br>About 95 per cent of Sri Lankan endemic birds and more than 50 per cent of endemic mammals are known to have their habitats in this Forest Reserve. <br><br>Year round, the forest is covered by plenty of rain clouds. It is one of the famous places to visit in Galle. <br><br>You can experience the leisurely pace of wildlife and the splendour of dense and copious evergreen rainforests. </p><br><hr><b>Location : </b>Sinharaja Forest Reserve, Southern Province<br><br><b>Timings : </b>Opens daily from 6:30 AM to 6 PM<br><br><b>Price : </b>Approximate price ranges from INR 260 to INR460 (664 LKR to 1160 LKR)','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3965.0022263218957!2d80.46596731452988!3d6.3937130953737125!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae3e2161cf9a38d%3A0x813bfa0e6b19f787!2sSinharaja%20Forest!5e0!3m2!1sen!2slk!4v1641348911257!5m2!1sen!2slk'),
('Sigiriya','sigiriya.jpg','sigiriya.jpg','<p>A visit to this place will show you an 1600 years old Sigiriya Fortress which was built by King Kasyapa. <br><br>This massive compound is protected by two moats and three ramparts. <br><br>It is once known to be the private residence of King Kasyapa and also one of the best places to visit in Sri Lanka.<br><br>If you are interested in ancient places, this is one of the best tourist places to visit in Sri Lanka.</p><br><hr><b>Location : </b>31 min (16.8 km) from Sri Lanka via Inamaluwa.<br><br><b>Timings : </b>Opens daily from 7 AM to 5:30 PM.<br><br><b>Best time to visit : </b>This area will be early in the morning or late in the afternoon.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3951.403337872044!2d80.75785241453987!3d7.957203494268707!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3afca15b724c9ab3%3A0xab1771275b370d52!2sSigiriya%20Rock!5e0!3m2!1sen!2slk!4v1641312370644!5m2!1sen!2slk'),
('Adam''s Rock','adams.jpg','adam.jpg','<p>Adam''s Peak is a famous mountain and tourist attraction having its summit at an altitude of 2243 m.<br><br> Also known as Sri Pada, (sacred footprint), the famous spot is situated in Southern Sri Lanka which is revered by Buddhists, Hindus, Christians and Muslims. <br><br>Embark on a fun and enthralling overnight trek to Adam''s Peak and climb up approximately 5500 steps to reach the summit. <br><br>Enjoy a magical sunrise from the top with your companions and create some lasting memories of this experience!</p><br><hr><b>Location : </b>Nallathaniya.<br><br><b>Age Group : </b>12-60 yrs.<br><br><b>Best time to visit : </b>3:30 PM (Day 1) to 9:30 PM (Day 2).','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15846.689655371065!2d80.49063343279172!3d6.809642771251774!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae3977589234b59%3A0x8723ad471d5b37dc!2sSri%20Pada%20%2F%20Adam&#39;s%20Peak!5e0!3m2!1sen!2slk!4v1645972799031!5m2!1sen!2slk'),
('World''s End','worldsend.webp',"world_s_end.jpg",'<p>One of the most jaw-dropping experience you can ever have in Sri Lanka is the World’s End on the Horton Plains. <br><br>Enjoy a tuk-tuk ride to the Horton plains from Nuwara Eliya and it is among the best tourist places to visit in Sri Lanka.<br><br>You can see animals such as leopards and deer. <br><br>Experience the amazing flora and fauna which will be an amazing experience.</p><br><hr><b>Location : </b>The nearest station is in Nanu Oya which is about 8km.<br><br><b>Highlights : </b>Baker’s fall which is truly spectacular<br><br><b>Best time to visit : </b>The best time to reach there is before 10:00 AM before it gets too cloudy because you will not be able to see anything after that.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3961.9145370189353!2d80.79227851453214!3d6.780255395099127!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae389cf46cb3f67%3A0x818e33bb2a32673a!2sGreat%20World&#39;s%20End%20Drop!5e0!3m2!1sen!2slk!4v1641320777358!5m2!1sen!2slk'),
('Unawatuna Beach','unawatuna.jpg','unawatuna.jpg','<p>Relax your senses in the sparkling waters well complemented with a lazy sandy idyll in Unawatuna beach. <br><br>It was once named the world''s best beach by Discovery Channel. <br><br>One and a half hour drive from Colombo makes it easier for people to reach this beach.</p><br><hr><b>Location : </b>A coastal town in the Galle district of Sri Lanka, Unawatuna is a suburb of Galle that is located at a distance of about 5 kilometres southeast to the city center and approximately 108 kilometres south of Sri Lanka’s capital city - Colombo<br><br><b>Timings : </b>Open 24 hours<br><br><b>Facilities : </b>Safe ocean swimming conditions, marine sports training and equipment provisions, yoga centres, spa, and massage centres.','https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7935.80549404774!2d80.24340564429929!3d6.008090732508506!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae172eebc19a0dd%3A0x1bcfa16fa4ddf516!2sUnawatuna%20Beach!5e0!3m2!1sen!2slk!4v1641437979434!5m2!1sen!2slk');
